"""empty message

Revision ID: 19fdbf94e93c
Revises: c1e26fa84341
Create Date: 2021-03-02 13:34:41.102865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fdbf94e93c'
down_revision = 'c1e26fa84341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('post', sa.Column('published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'published')
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
