"""empty message

Revision ID: 27eb402e69c3
Revises: adb891c4bf3a
Create Date: 2021-03-30 15:47:51.588766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27eb402e69c3'
down_revision = 'adb891c4bf3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('post', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
