"""empty message

Revision ID: 3f2f7875cb91
Revises: 27eb402e69c3
Create Date: 2021-03-30 15:48:55.823678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2f7875cb91'
down_revision = '27eb402e69c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('post', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
