"""empty message

Revision ID: adb891c4bf3a
Revises: 19fdbf94e93c
Create Date: 2021-03-30 15:27:37.355446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb891c4bf3a'
down_revision = '19fdbf94e93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sa.String(length=64), nullable=False))
    op.alter_column('post', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('post', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###
